apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sBlockLatest
metadata:
  name: block-latest
spec:
  enforcementAction: deny  
  match:
    # namespaces: ["flower-ns"]
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]