apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8sdeploymentimagetag
spec:
  crd:
    spec:
      names:
        kind: K8sDeploymentImageTag
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sdeploymentimagetag

        violation[{"msg": msg}] {
          input.review.kind.kind == "Deployment"

          containers := input.review.object.spec.template.spec.containers
          container := containers[_]

          endswith(container.image, ":latest")

          msg := sprintf("Deployment '%s' uses forbidden image tag ':latest'", [input.review.object.metadata.name])
        }